// This file is auto-generated by @hey-api/openapi-ts

export type Body_contacts_import_contacts = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_uploads_upload_photo_endpoint = {
    file: string;
};

export type BulkExportRequest = {
    ids?: (Array<(string)> | null);
    format?: string;
};

export type BulkUpdateRequest = {
    ids: Array<(string)>;
    data: ContactUpdate;
};

export type ContactCreate = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    category?: string;
    tags?: Array<(string)>;
    linkedin_url?: (string | null);
    facebook_url?: (string | null);
    photo_url?: (string | null);
    relationship_strength?: number;
    first_met?: (string | null);
    notes?: (string | null);
};

export type ContactPublic = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    category?: string;
    tags?: Array<(string)>;
    linkedin_url?: (string | null);
    facebook_url?: (string | null);
    photo_url?: (string | null);
    relationship_strength?: number;
    first_met?: (string | null);
    notes?: (string | null);
    id: string;
    user_id: string;
    created_at?: (string | null);
};

export type ContactsPublic = {
    data: Array<ContactPublic>;
    count: number;
};

export type ContactUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    category?: (string | null);
    tags?: (Array<(string)> | null);
    linkedin_url?: (string | null);
    facebook_url?: (string | null);
    photo_url?: (string | null);
    relationship_strength?: (number | null);
    first_met?: (string | null);
    notes?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TagCount = {
    name: string;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ContactsReadTagsResponse = (Array<TagCount>);

export type ContactsReadContactsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    tag?: (string | null);
};

export type ContactsReadContactsResponse = (ContactsPublic);

export type ContactsCreateContactData = {
    requestBody: ContactCreate;
};

export type ContactsCreateContactResponse = (ContactPublic);

export type ContactsReadContactData = {
    id: string;
};

export type ContactsReadContactResponse = (ContactPublic);

export type ContactsUpdateContactData = {
    id: string;
    requestBody: ContactUpdate;
};

export type ContactsUpdateContactResponse = (ContactPublic);

export type ContactsDeleteContactData = {
    id: string;
};

export type ContactsDeleteContactResponse = (Message);

export type ContactsBulkDeleteContactsData = {
    requestBody: Array<(string)>;
};

export type ContactsBulkDeleteContactsResponse = (Message);

export type ContactsExportContactsData = {
    requestBody: BulkExportRequest;
};

export type ContactsExportContactsResponse = (unknown);

export type ContactsImportContactsData = {
    formData: Body_contacts_import_contacts;
};

export type ContactsImportContactsResponse = (unknown);

export type ContactsBulkUpdateContactsData = {
    requestBody: BulkUpdateRequest;
};

export type ContactsBulkUpdateContactsResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UploadsUploadPhotoEndpointData = {
    formData: Body_uploads_upload_photo_endpoint;
};

export type UploadsUploadPhotoEndpointResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);