// This file is auto-generated by @hey-api/openapi-ts

/**
 * Returned once when a key is created; the plaintext key is shown only here.
 */
export type ApiKeyCreated = {
    name: string;
    id: string;
    created_at?: (string | null);
    revoked_at?: (string | null);
    key: string;
};

export type ApiKeyCreateIn = {
    name: string;
};

export type ApiKeyPublic = {
    name: string;
    id: string;
    created_at?: (string | null);
    revoked_at?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_uploads_upload_photo_endpoint = {
    file: string;
};

export type HelloWorldRunIn = {
    name?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
    tags?: Array<(string)>;
    photo_url?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    tags?: Array<(string)>;
    photo_url?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    tags?: (Array<(string)> | null);
    photo_url?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RunOut = {
    id: (number | null);
    job_id: (number | null);
    job: string;
    source: string;
    args?: ({
    [key: string]: unknown;
} | null);
    tags?: (Array<(string)> | null);
    status: string;
    progress?: (number | null);
    error?: (string | null);
    worker_id?: (string | null);
    scheduled_at?: (string | null);
    created_at?: (string | null);
    started_at?: (string | null);
    finished_at?: (string | null);
    tasks?: Array<TaskOut>;
};

export type TagCount = {
    name: string;
    count: number;
};

export type TaskOut = {
    id: (number | null);
    position: number;
    task_name: string;
    status: string;
    attempts: number;
    error?: (string | null);
    started_at?: (string | null);
    finished_at?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ApiKeysListApiKeysResponse = (Array<ApiKeyPublic>);

export type ApiKeysCreateApiKeyData = {
    requestBody: ApiKeyCreateIn;
};

export type ApiKeysCreateApiKeyResponse = (ApiKeyCreated);

export type ApiKeysRevokeApiKeyData = {
    apiKeyId: string;
};

export type ApiKeysRevokeApiKeyResponse = (Message);

export type ItemsReadItemTagsResponse = (Array<TagCount>);

export type ItemsReadItemsData = {
    excludeTags?: (string | null);
    includeTags?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    sort?: (string | null);
    tag?: (string | null);
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsListRunsData = {
    limit?: number;
    offset?: number;
    tag?: (string | null);
};

export type JobsListRunsResponse = (Array<RunOut>);

export type JobsEnqueueHelloWorldData = {
    requestBody: HelloWorldRunIn;
};

export type JobsEnqueueHelloWorldResponse = (RunOut);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UploadsUploadPhotoEndpointData = {
    formData: Body_uploads_upload_photo_endpoint;
};

export type UploadsUploadPhotoEndpointResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsAppVersionResponse = (unknown);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);