"""Add photo_url to contacts

Revision ID: 4a31c67d81c2
Revises: eda0c5b8a9d3
Create Date: 2026-07-29 11:40:02.273297

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a31c67d81c2'
down_revision = 'eda0c5b8a9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('contact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contact', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('contact', 'first_met',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('contact', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_index(op.f('ix_contact_user_id'), table_name='contact')
    op.drop_constraint(op.f('uq_contact_user_email'), 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_contact_user_email'), 'contact', ['user_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_contact_user_id'), 'contact', ['user_id'], unique=False)
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.alter_column('contact', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('contact', 'first_met',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contact', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('contact', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contact', 'photo_url')
    # ### end Alembic commands ###
