"""Add photo_url to items

Revision ID: e4671e74a8d3
Revises: f849ea06f5b3
Create Date: 2026-08-01 03:21:52.392789

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e4671e74a8d3'
down_revision = 'f849ea06f5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'photo_url')
    # ### end Alembic commands ###
